-- =====================================================
-- COMPLETE MISSING COLUMNS ALTER SCRIPT
-- Ez_Biz_Barber Application - OPERATIONAL.BARBER Schema
-- =====================================================

-- CUSTOMER table missing columns
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN IF NOT EXISTS BILLING_ADDRESS VARCHAR(255);
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN IF NOT EXISTS BILLING_CITY VARCHAR(100);
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN IF NOT EXISTS BILLING_STATE VARCHAR(50);
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN IF NOT EXISTS BILLING_ZIP VARCHAR(20);
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN IF NOT EXISTS PRIMARY_STREET VARCHAR(255);
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN IF NOT EXISTS SERVICE_STREET VARCHAR(255);
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN IF NOT EXISTS TEXT_FLAG BOOLEAN DEFAULT FALSE;
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN IF NOT EXISTS MEMBER_FLAG BOOLEAN DEFAULT FALSE;
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN IF NOT EXISTS PRIMARY_CONTACT_METHOD VARCHAR(50) DEFAULT 'Phone';
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN IF NOT EXISTS COMMENTS TEXT;
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN IF NOT EXISTS LAST_UPDATED_AT TIMESTAMP_NTZ;

-- ACCOUNTS table missing columns
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS ADD COLUMN IF NOT EXISTS CONTACT_PERSON VARCHAR(200);
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS ADD COLUMN IF NOT EXISTS BILLING_ADDRESS VARCHAR(255);
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS ADD COLUMN IF NOT EXISTS CITY VARCHAR(100);
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS ADD COLUMN IF NOT EXISTS STATE VARCHAR(50);
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS ADD COLUMN IF NOT EXISTS ZIP_CODE VARCHAR(20);
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS ADD COLUMN IF NOT EXISTS ACCOUNT_TYPE VARCHAR(100) DEFAULT 'Commercial';
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS ADD COLUMN IF NOT EXISTS ACCOUNT_DESCRIPTION TEXT;

-- EMPLOYEE table missing columns
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE ADD COLUMN IF NOT EXISTS DEPARTMENT VARCHAR(100);
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE ADD COLUMN IF NOT EXISTS HOURLY_WAGE DECIMAL(10,2);
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE ADD COLUMN IF NOT EXISTS ACTIVE_STATUS BOOLEAN DEFAULT TRUE;
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE ADD COLUMN IF NOT EXISTS TERMINATION_DATE DATE;
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE ADD COLUMN IF NOT EXISTS TERMINATION_REASON TEXT;
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE ADD COLUMN IF NOT EXISTS MODIFIED_DATE TIMESTAMP_NTZ;

-- SERVICES table missing columns
ALTER TABLE OPERATIONAL.BARBER.SERVICES ADD COLUMN IF NOT EXISTS SERVICE_DESCRIPTION TEXT;
ALTER TABLE OPERATIONAL.BARBER.SERVICES ADD COLUMN IF NOT EXISTS ACTIVE_STATUS BOOLEAN DEFAULT TRUE;

-- SERVICE_ADDRESSES table missing columns
ALTER TABLE OPERATIONAL.BARBER.SERVICE_ADDRESSES ADD COLUMN IF NOT EXISTS STREET_ADDRESS VARCHAR(255);
ALTER TABLE OPERATIONAL.BARBER.SERVICE_ADDRESSES ADD COLUMN IF NOT EXISTS ACCOUNT_ID NUMBER;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_ADDRESSES ADD COLUMN IF NOT EXISTS SQUARE_FOOTAGE NUMBER DEFAULT 0;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_ADDRESSES ADD COLUMN IF NOT EXISTS LAST_UPDATED_AT TIMESTAMP_NTZ;

-- BUSINESS_SESSIONS table missing columns
ALTER TABLE OPERATIONAL.BARBER.BUSINESS_SESSIONS ADD COLUMN IF NOT EXISTS MODIFIED_AT TIMESTAMP_NTZ;

-- Create RATE_LIMIT_LOG table structure (recreate to ensure all columns)
DROP TABLE IF EXISTS OPERATIONAL.BARBER.RATE_LIMIT_LOG;
CREATE TABLE OPERATIONAL.BARBER.RATE_LIMIT_LOG (
    LOG_ID NUMBER IDENTITY(1,1) PRIMARY KEY,
    IP_ADDRESS VARCHAR(45) NOT NULL,
    ACTION_TYPE VARCHAR(50) NOT NULL,
    PORTAL_USER_ID NUMBER,
    ATTEMPT_COUNT NUMBER DEFAULT 1,
    FIRST_ATTEMPT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_ATTEMPT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ENDPOINT VARCHAR(255),
    REQUEST_COUNT NUMBER DEFAULT 1,
    WINDOW_START TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BLOCKED BOOLEAN DEFAULT FALSE
);

-- SERVICE_TRANSACTION table missing columns
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS COMPLETION_DATE DATE;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS DISCOUNT DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS AMOUNT_RECEIVED DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS PYMT_MTHD_1 VARCHAR(50);
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS PYMT_MTHD_1_AMT DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS PYMT_MTHD_2 VARCHAR(50);
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS PYMT_MTHD_2_AMT DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS EMPLOYEE1_ID NUMBER;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS EMPLOYEE2_ID NUMBER;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS EMPLOYEE3_ID NUMBER;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS BASE_SERVICE_COST DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS TOTAL_LABOR_COST DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS MATERIAL_COST DECIMAL(10,2) DEFAULT 0.00;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS PRICE_ADJUSTMENTS_JSON TEXT;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS BOOKING_ORIGIN VARCHAR(50) DEFAULT 'ADMIN';
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS ADDRESS_ID NUMBER;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS DEPOSIT DECIMAL(10,2) DEFAULT 0;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS DEPOSIT_PAID BOOLEAN DEFAULT FALSE;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS DEPOSIT_PAYMENT_METHOD VARCHAR(50);
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS PRICING_STRATEGY VARCHAR(100);
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS MARKUP_PERCENTAGE DECIMAL(5,2);
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS IS_RECURRING BOOLEAN DEFAULT FALSE;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_TRANSACTION ADD COLUMN IF NOT EXISTS RECURRENCE_PATTERN VARCHAR(100);

-- CUSTOMER_PORTAL_USERS missing columns
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER_PORTAL_USERS ADD COLUMN IF NOT EXISTS FAILED_LOGIN_ATTEMPTS NUMBER DEFAULT 0;
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER_PORTAL_USERS ADD COLUMN IF NOT EXISTS ACCOUNT_LOCKED BOOLEAN DEFAULT FALSE;
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER_PORTAL_USERS ADD COLUMN IF NOT EXISTS ACCOUNT_LOCKED_UNTIL TIMESTAMP_NTZ;
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER_PORTAL_USERS ADD COLUMN IF NOT EXISTS LAST_LOGIN_DATE TIMESTAMP_NTZ;
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER_PORTAL_USERS ADD COLUMN IF NOT EXISTS PASSWORD_RESET_TOKEN VARCHAR(255);
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER_PORTAL_USERS ADD COLUMN IF NOT EXISTS PASSWORD_RESET_EXPIRY TIMESTAMP_NTZ;
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER_PORTAL_USERS ADD COLUMN IF NOT EXISTS EMAIL_VERIFIED BOOLEAN DEFAULT FALSE;
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER_PORTAL_USERS ADD COLUMN IF NOT EXISTS IS_ACTIVE BOOLEAN DEFAULT TRUE;

-- BUSINESS_PORTAL_USERS missing columns  
ALTER TABLE OPERATIONAL.BARBER.BUSINESS_PORTAL_USERS ADD COLUMN IF NOT EXISTS FAILED_LOGIN_ATTEMPTS NUMBER DEFAULT 0;
ALTER TABLE OPERATIONAL.BARBER.BUSINESS_PORTAL_USERS ADD COLUMN IF NOT EXISTS ACCOUNT_LOCKED BOOLEAN DEFAULT FALSE;
ALTER TABLE OPERATIONAL.BARBER.BUSINESS_PORTAL_USERS ADD COLUMN IF NOT EXISTS ACCOUNT_LOCKED_UNTIL TIMESTAMP_NTZ;
ALTER TABLE OPERATIONAL.BARBER.BUSINESS_PORTAL_USERS ADD COLUMN IF NOT EXISTS LAST_LOGIN_DATE TIMESTAMP_NTZ;
ALTER TABLE OPERATIONAL.BARBER.BUSINESS_PORTAL_USERS ADD COLUMN IF NOT EXISTS PASSWORD_RESET_TOKEN VARCHAR(255);
ALTER TABLE OPERATIONAL.BARBER.BUSINESS_PORTAL_USERS ADD COLUMN IF NOT EXISTS PASSWORD_RESET_EXPIRY TIMESTAMP_NTZ;
ALTER TABLE OPERATIONAL.BARBER.BUSINESS_PORTAL_USERS ADD COLUMN IF NOT EXISTS IS_ACTIVE BOOLEAN DEFAULT TRUE;

-- Fix column name inconsistencies
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS RENAME COLUMN IF EXISTS BILLING_ADDRESS_1 TO BILLING_ADDRESS;
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS RENAME COLUMN IF EXISTS BILLING_CITY TO CITY;
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS RENAME COLUMN IF EXISTS BILLING_STATE TO STATE;
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS RENAME COLUMN IF EXISTS BILLING_ZIP TO ZIP_CODE;

ALTER TABLE OPERATIONAL.BARBER.SERVICES RENAME COLUMN IF EXISTS DESCRIPTION TO SERVICE_DESCRIPTION;
ALTER TABLE OPERATIONAL.BARBER.SERVICES RENAME COLUMN IF EXISTS IS_ACTIVE TO ACTIVE_STATUS;

ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE RENAME COLUMN IF EXISTS HOURLY_RATE TO HOURLY_WAGE;
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE RENAME COLUMN IF EXISTS STATUS TO ACTIVE_STATUS;
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE RENAME COLUMN IF EXISTS MODIFIED_AT TO MODIFIED_DATE;

ALTER TABLE OPERATIONAL.BARBER.SERVICE_ADDRESSES RENAME COLUMN IF EXISTS ADDRESS_LINE1 TO STREET_ADDRESS;