-- Detailed Column Comparison Script
-- Run this for each table to compare column structures

-- Example: Compare CUSTOMER table columns between schemas
SELECT 
    'CARPET_CUSTOMER' as SOURCE,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    ORDINAL_POSITION
FROM OPERATIONAL.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'CARPET' 
    AND TABLE_NAME = 'CUSTOMER'
ORDER BY ORDINAL_POSITION;

SELECT 
    'BARBER_CUSTOMER' as SOURCE,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    ORDINAL_POSITION
FROM OPERATIONAL.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'BARBER' 
    AND TABLE_NAME = 'CUSTOMER'
ORDER BY ORDINAL_POSITION;

-- Show column differences for CUSTOMER table
SELECT 'ONLY_IN_CARPET_CUSTOMER' as DIFFERENCE_TYPE, COLUMN_NAME, DATA_TYPE
FROM OPERATIONAL.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'CARPET' AND TABLE_NAME = 'CUSTOMER'
    AND COLUMN_NAME NOT IN (
        SELECT COLUMN_NAME 
        FROM OPERATIONAL.INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = 'BARBER' AND TABLE_NAME = 'CUSTOMER'
    )
UNION ALL
SELECT 'ONLY_IN_BARBER_CUSTOMER' as DIFFERENCE_TYPE, COLUMN_NAME, DATA_TYPE
FROM OPERATIONAL.INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'BARBER' AND TABLE_NAME = 'CUSTOMER'
    AND COLUMN_NAME NOT IN (
        SELECT COLUMN_NAME 
        FROM OPERATIONAL.INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = 'CARPET' AND TABLE_NAME = 'CUSTOMER'
    );

-- Compare other critical tables (repeat pattern above)
-- Replace 'CUSTOMER' with: ACCOUNTS, RATE_LIMIT_LOG, SERVICES, EMPLOYEE, etc.