-- Schema Comparison Script
-- Run this in Snowflake to compare OPERATIONAL.CARPET vs OPERATIONAL.BARBER

-- Get all tables in CARPET schema
SELECT 
    'CARPET' as SCHEMA_NAME,
    TABLE_NAME,
    TABLE_TYPE
FROM OPERATIONAL.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'CARPET'
    AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

-- Get all tables in BARBER schema  
SELECT 
    'BARBER' as SCHEMA_NAME,
    TABLE_NAME,
    TABLE_TYPE
FROM OPERATIONAL.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'BARBER'
    AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

-- Compare table counts
SELECT 
    'TABLE_COUNT_COMPARISON' as COMPARISON_TYPE,
    (SELECT COUNT(*) FROM OPERATIONAL.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'CARPET' AND TABLE_TYPE = 'BASE TABLE') as CARPET_COUNT,
    (SELECT COUNT(*) FROM OPERATIONAL.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'BARBER' AND TABLE_TYPE = 'BASE TABLE') as BARBER_COUNT;

-- Show tables that exist in one schema but not the other
SELECT 'ONLY_IN_CARPET' as DIFFERENCE_TYPE, TABLE_NAME
FROM OPERATIONAL.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'CARPET' 
    AND TABLE_TYPE = 'BASE TABLE'
    AND TABLE_NAME NOT IN (
        SELECT TABLE_NAME 
        FROM OPERATIONAL.INFORMATION_SCHEMA.TABLES 
        WHERE TABLE_SCHEMA = 'BARBER' AND TABLE_TYPE = 'BASE TABLE'
    )
UNION ALL
SELECT 'ONLY_IN_BARBER' as DIFFERENCE_TYPE, TABLE_NAME
FROM OPERATIONAL.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'BARBER' 
    AND TABLE_TYPE = 'BASE TABLE'
    AND TABLE_NAME NOT IN (
        SELECT TABLE_NAME 
        FROM OPERATIONAL.INFORMATION_SCHEMA.TABLES 
        WHERE TABLE_SCHEMA = 'CARPET' AND TABLE_TYPE = 'BASE TABLE'
    );