-- Create missing tables in OPERATIONAL.BARBER to match OPERATIONAL.CARPET

-- Create USER_CREDENTIALS table
CREATE OR REPLACE TABLE OPERATIONAL.BARBER.USER_CREDENTIALS ( 
    USER_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER, 
    USERNAME VARCHAR(100) NOT NULL, 
    PASSWORD_HASH VARCHAR(255) NOT NULL, 
    ROLE VARCHAR(50) DEFAULT 'user', 
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(), 
    UNIQUE (USERNAME), 
    PRIMARY KEY (USER_ID) 
);

-- Create MATERIALS table
CREATE OR REPLACE TABLE OPERATIONAL.BARBER.MATERIALS ( 
    ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER, 
    PRODUCT_NAME VARCHAR(16777216), 
    PRODUCT_COST NUMBER(10,2), 
    SUPPLIER_NAME VARCHAR(16777216), 
    SUPPLIER_CONTACT_NAME VARCHAR(16777216), 
    SUPPLIER_CONTACT_NUMBER VARCHAR(16777216), 
    PRODUCT_QUANTITY NUMBER(38,0), 
    PRIMARY KEY (ID) 
);

-- Create CUSTOMER_LEADS table
CREATE OR REPLACE TABLE OPERATIONAL.BARBER.CUSTOMER_LEADS ( 
    PROSPECTIVE_CUSTOMER_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER, 
    FIRST_NAME VARCHAR(16777216) NOT NULL, 
    LAST_NAME VARCHAR(16777216) NOT NULL, 
    EMAIL VARCHAR(16777216), 
    PHONE_NUMBER VARCHAR(16777216), 
    STREET_ADDRESS VARCHAR(16777216), 
    CITY VARCHAR(16777216), 
    STATE VARCHAR(16777216), 
    ZIP_CODE NUMBER(38,0), 
    LEAD_SOURCE VARCHAR(16777216), 
    CREATED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(), 
    LAST_MODIFIED_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(), 
    PRIMARY KEY (PROSPECTIVE_CUSTOMER_ID) 
);