-- Migration script to update existing OPERATIONAL.BARBER schema to match OPERATIONAL.CARPET
-- Run this in your Snowflake environment to fix existing tables

-- Fix CUSTOMER table - Add missing columns
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN BILLING_ADDRESS VARCHAR(255);
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN BILLING_CITY VARCHAR(100);
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN BILLING_STATE VARCHAR(50);
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN BILLING_ZIP VARCHAR(20);
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN PRIMARY_STREET VARCHAR(255);
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN SERVICE_STREET VARCHAR(255);
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN TEXT_FLAG BOOLEAN DEFAULT FALSE;
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN MEMBER_FLAG BOOLEAN DEFAULT FALSE;
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN PRIMARY_CONTACT_METHOD VARCHAR(50) DEFAULT 'Phone';
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN COMMENTS TEXT;
ALTER TABLE OPERATIONAL.BARBER.CUSTOMER ADD COLUMN LAST_UPDATED_AT TIMESTAMP_NTZ;

-- Fix RATE_LIMIT_LOG table - Add missing columns
ALTER TABLE OPERATIONAL.BARBER.RATE_LIMIT_LOG ADD COLUMN ACTION_TYPE VARCHAR(50);
ALTER TABLE OPERATIONAL.BARBER.RATE_LIMIT_LOG ADD COLUMN ATTEMPT_COUNT NUMBER DEFAULT 1;
ALTER TABLE OPERATIONAL.BARBER.RATE_LIMIT_LOG ADD COLUMN FIRST_ATTEMPT TIMESTAMP_NTZ;
ALTER TABLE OPERATIONAL.BARBER.RATE_LIMIT_LOG ADD COLUMN LAST_ATTEMPT TIMESTAMP_NTZ;

-- Fix ACCOUNTS table - Rename columns
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS RENAME COLUMN BILLING_ADDRESS_1 TO BILLING_ADDRESS;
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS RENAME COLUMN BILLING_CITY TO CITY;
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS RENAME COLUMN BILLING_STATE TO STATE;
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS RENAME COLUMN BILLING_ZIP TO ZIP_CODE;
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS ADD COLUMN ACCOUNT_TYPE VARCHAR(100) DEFAULT 'Commercial';
ALTER TABLE OPERATIONAL.BARBER.ACCOUNTS ADD COLUMN ACCOUNT_DESCRIPTION TEXT;

-- Fix SERVICES table - Rename columns
ALTER TABLE OPERATIONAL.BARBER.SERVICES RENAME COLUMN DESCRIPTION TO SERVICE_DESCRIPTION;
ALTER TABLE OPERATIONAL.BARBER.SERVICES RENAME COLUMN IS_ACTIVE TO ACTIVE_STATUS;

-- Fix EMPLOYEE table - Add and rename columns
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE ADD COLUMN DEPARTMENT VARCHAR(100);
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE RENAME COLUMN HOURLY_RATE TO HOURLY_WAGE;
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE RENAME COLUMN STATUS TO ACTIVE_STATUS;
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE ADD COLUMN TERMINATION_DATE DATE;
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE ADD COLUMN TERMINATION_REASON TEXT;
ALTER TABLE OPERATIONAL.BARBER.EMPLOYEE RENAME COLUMN MODIFIED_AT TO MODIFIED_DATE;

-- Fix SERVICE_ADDRESSES table
ALTER TABLE OPERATIONAL.BARBER.SERVICE_ADDRESSES RENAME COLUMN ADDRESS_LINE1 TO STREET_ADDRESS;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_ADDRESSES ADD COLUMN ACCOUNT_ID NUMBER;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_ADDRESSES ADD COLUMN SQUARE_FOOTAGE NUMBER DEFAULT 0;
ALTER TABLE OPERATIONAL.BARBER.SERVICE_ADDRESSES ADD COLUMN LAST_UPDATED_AT TIMESTAMP_NTZ;

-- Fix BUSINESS_SESSIONS table
ALTER TABLE OPERATIONAL.BARBER.BUSINESS_SESSIONS ADD COLUMN MODIFIED_AT TIMESTAMP_NTZ;

-- Update foreign key constraint for SERVICE_ADDRESSES if needed
-- ALTER TABLE OPERATIONAL.BARBER.SERVICE_ADDRESSES ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES OPERATIONAL.BARBER.ACCOUNTS(ACCOUNT_ID);