# Streamlit Secrets Template
# Copy this file to .streamlit/secrets.toml and fill in your actual values
# This template file can be safely committed to version control

[snowflake]
account = "your-snowflake-account-identifier"  # e.g. "abc12345.us-east-1"
user = "your-snowflake-username"
password = "your-snowflake-password"
warehouse = "your-warehouse-name"  # e.g. "COMPUTE_WH"
database = "your-database-name"    # e.g. "OPERATIONAL"
schema = "BARBER"                  # Keep as BARBER for this instance
role = "your-role-name"           # e.g. "ACCOUNTADMIN"

[email]
smtp_server = "smtp.gmail.com"    # Gmail SMTP server
smtp_port = 587                   # Gmail SMTP port
email_address = "your-email@gmail.com"
email_password = "your-app-password"  # Use Gmail App Password, not regular password

[business]
business_name = "Your Barber Shop Name"
contact_email = "info@yourbarbershop.com"
contact_phone = "(555) 123-4567"

[app]
debug_mode = false
session_timeout = 3600